apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpndwpNVEV5TVRKYUZ3MDBNekF4TWpnd01URXlNVEphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFET21Dcm5EcUlTN253UnRDcDBWVWVXKzdabWpvUzFkZVpOSFVmU2IvWllvYVRnMWUxdwpBSlhGZ0lmNDdUMjdwOHk0d0J0bXVsd1Y0VEJ0RHY0OXNZbXBmRmhyeUovbEE0TGt4Q244TEE0amVsNTcxbENQCnJETmxjN1hQN285S0lOeXpNcW9ZaHpadThsMTNXaHpETk1HanE3WEJFZUU4U0xrc1dqMENWVlBUdjRvWEZ2YUYKRmZ2c0cxdnlIZmFId1k0L2RzZnBCWWNHZW0wNmJGRzZ1czJuNUREN29OSG9QRmYyNE1GenF5cU5hcTZ1RFJ0SwpNNEEwc2J0SGIzY2ZJbE1uZEE3NUZyd0ExQXV5YjVHVXhCNDRIQXFUTE1OOUViVFFvTUJicHJhWWR0amFjc2Z5CmEzeSt6dGszSWtWN0dXSy9CeCt6a1U0WitmaHNra0ZHbm43NUFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQ5T0J2VVF4bG5rUWh3YzQvNwpoZEM5SjZ1KzZEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrSjhSY2ZSdW1PcExnN0ZXSWU0Q2tncVBhbEJ4CnVFNmtROHFuV2ZUL25OMHhQdWg0ajRzNVF6TWJiU3NaaVRKam82bTB4NE1OQW52d1liRENYR0xSSkZwZEhzaysKTTErNFFpZytrWEh1UzRXQTh2OENhWU1KT0QxS0wzZFNONm1KUGFZMjFnZFRGcG1oWlIzREQ5enFBOFI2NFFoVQp2b2pnTUp2RS9HeTM5Q2E3a3ljdE9FTSs2ajg5ZlhwbERaaUplejVUWE92R0xvVjBlVTJKNGNRQzE2enVscm9xClp3d0V6SjIvNXhnSzFqV0tKTXpLQ1U3aFJ4QUNhMVBaQmM3SUQwbWNZc2xxUHFUa2lia2ppM0N1VFE4OE5CRHoKVTRnczJQY0hjUHpSbmtNRkRualdDamgzdTVtNHlReGVUekU0M1dqTmVJZXBXejZyS0RCazBWeHVlQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5f6fc49a-7373-498f-9dfa-90f70e3eb6f6.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_2b6a042bd811cc7462d43b6668913edb3a8fb7ac8bf14f99a8782fba7b3c6e55
